package quidditchgame.menus;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 * Class MenuHowtoplayPanel
 * This is the second page of the instructions.
 * 
 * @author Jimmy Yuan,  Ben Han
 */
public class MenuHowtoplayPanel extends javax.swing.JPanel {

    private Menu parent;
    /**
     * Creates new form MenuHowtoplayPanel
     * @param m reference to the parent Menu class object
     */
    public MenuHowtoplayPanel(Menu m) {
        parent = m;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuButton = new javax.swing.JButton();
        PreviousButton = new javax.swing.JButton();

        mainMenuButton.setText("Return to Main Menu");
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        PreviousButton.setText("Previous Page");
        PreviousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(mainMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addComponent(PreviousButton)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(452, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainMenuButton)
                    .addComponent(PreviousButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Menu button to go back to menu
     * @param evt Button event
     */
    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        parent.mainMenu();
    }//GEN-LAST:event_mainMenuButtonActionPerformed

    /**
     * Previous button to go to the previous instruction page
     * @param evt Button event
     */
    private void PreviousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousButtonActionPerformed
        parent.instructions();
    }//GEN-LAST:event_PreviousButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PreviousButton;
    private javax.swing.JButton mainMenuButton;
    // End of variables declaration//GEN-END:variables


    /**
     * Draws the background and instruction images
     * @param g Graphics object to draw with
     */
    @Override
    public void paintComponent(Graphics g )
    {
        super.paintComponent( g );
        // draws the back ground the image and the instruction image
        Image bgImage1 = new ImageIcon("./assets/gameIns.png").getImage();
        Image insImage1 = new ImageIcon("./assets/Instruction2.png").getImage();
        g.drawImage(bgImage1, 0, 0, null); 
        g.drawImage(insImage1, 100, 80, null); 
    }
}
