package quidditchgame.menus;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 * Class MenuMainPanel.
 * The main menu that is presented when the user first starts the game.
 * From this menu all other menus may be accessed.
 * 
 * @author  Jimmy Yuan,  Ben Han
 */
public class MenuMainPanel extends javax.swing.JPanel {

    private Menu parent;
    
    /** Creates new form MenuMainPanel
     *
     * @param m parent Menu object that handles events
     * @param paused Indicates whether the game is paused and whether to enable
     * the resume game button on the menu
     */
    public MenuMainPanel(Menu m, boolean paused) {
        parent = m;
        initComponents();
        resumeButton.setEnabled(paused);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newGameButton = new javax.swing.JButton();
        resumeButton = new javax.swing.JButton();
        instructionsButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(254, 254, 254));
        setMaximumSize(new java.awt.Dimension(1000, 630));
        setMinimumSize(new java.awt.Dimension(1000, 630));
        setPreferredSize(new java.awt.Dimension(1000, 630));

        newGameButton.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        newGameButton.setText("New Game");
        newGameButton.setPreferredSize(new java.awt.Dimension(84, 50));
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

        resumeButton.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        resumeButton.setText("Resume Game");
        resumeButton.setEnabled(false);
        resumeButton.setPreferredSize(new java.awt.Dimension(84, 50));
        resumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeButtonActionPerformed(evt);
            }
        });

        instructionsButton.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        instructionsButton.setText("Instructions");
        instructionsButton.setPreferredSize(new java.awt.Dimension(84, 50));
        instructionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructionsButtonActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        exitButton.setText("Exit");
        exitButton.setPreferredSize(new java.awt.Dimension(84, 50));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                    .addComponent(instructionsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                    .addComponent(resumeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                    .addComponent(newGameButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
                .addGap(292, 292, 292))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(283, Short.MAX_VALUE)
                .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resumeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(instructionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Event handler for "Exit" button clicks.
     * @param evt Button event
     */
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        parent.exitGame();
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * Event handler for "New Game" button clicks.
     * @param evt Button event
     */
    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
        parent.gameSetup();
    }//GEN-LAST:event_newGameButtonActionPerformed

    /**
     * Event handler for "Instructions" button clicks.
     * @param evt Button event
     */
    private void instructionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionsButtonActionPerformed
        parent.instructions();
    }//GEN-LAST:event_instructionsButtonActionPerformed

    /**
     * Event handler for "Resume game" button clicks.
     * @param evt Button event
     */
    private void resumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeButtonActionPerformed
        parent.resumeGame();
    }//GEN-LAST:event_resumeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JButton instructionsButton;
    private javax.swing.JButton newGameButton;
    private javax.swing.JButton resumeButton;
    // End of variables declaration//GEN-END:variables


    /**
     * Override function to draw the background
     * @param g Graphics object to draw with
     */
    @Override
    public void paintComponent(Graphics g )
    {
        super.paintComponent( g );
        // draws the background image
        Image bgImage1 = new ImageIcon("./assets/bkimg.png").getImage();
        g.drawImage(bgImage1, 0, 0, null); 
    }
}
